################################################
# Server configurations
################################################

# Set server params
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

################################################
# Application configurations
################################################
application:
  # Absolute path to GroupDocs license file
  licensePath: /Users/Alex/Documents/GroupDocs.Viewer.lic
  # Directory where all original files are stored
  filesDirectory: /Users/Alex/Documents/GroupDocs/
  # Directory all custom fonts are stored
  fontsDirectory: /Users/Alex/Projects/Fonts/CustomFonts/

resources:
  # Run application as service (only public API)
  runAsService: false
  ##############################################
  # All params above are required when runAsService: false
  ##############################################
  # Url/link to web resources (html, js, css, etc) archive
  resourcesUrl: https://github.com/bobkovalex/QuickView/archive/master.zip
  # Enable/disable resources downloading, false for download
  offlineMode: true
  # Set default document to view
  defaultDocument: ''
  # Enable/disable HTMl rendering mode, false for image mode
  htmlMode: true
  # Pages to be loaded on document open, 0 for all
  preloadPageCount: 2
  # Enable/disable rewrite for uploaded file if file with the same name already exists
  rewrite: true
  # Enable/disable document zoom
  zoom: true
  # Enable/disable page navigation
  pageSelector: true
  # Enable/disable text search
  search: true
  # Enable/disable thumbnails
  thumbnails: true
  # Enable/disable page rotation
  rotate: true
  # Enable/disable document download
  download: true
  # Enable/disable document upload
  upload: true
  # Enable/disable document print
  print: true
  # Enable/disable documents browse
  browse: true