################################################
# Server configurations
################################################

# Set server params
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

################################################
# Application configurations
################################################
application:
  # Absolute path to GroupDocs license file
  licensePath: /Users/Alex/Documents/GroupDocs.Viewer.lic
  # Directory where all original files are stored
  filesDirectory: /Users/Alex/Documents/GroupDocs/
  # Directory all custom fonts are stored
  fontsDirectory: /Users/Alex/Projects/Fonts/CustomFonts/

resources:
  # Run application as service (only public API)
  runAsService: false
  # Url/link to web resources (html, js, css, etc) archive
  # Required when runAsService: false
  resourcesUrl: https://github.com/bobkovalex/QuickView/archive/master.zip